/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.spicesoftware.gui.common;

/**
 * @author Cupmouse
 */
public class SpicePanelOKCancelButtons extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    // End of variables declaration//GEN-END:variables


    /**
     * Creates new form SpicePanelOKCancelButtons
     */
    public SpicePanelOKCancelButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        buttonOK.setText("決定");
        add(buttonOK);

        buttonCancel.setText("キャンセル");
        add(buttonCancel);
    }// </editor-fold>//GEN-END:initComponents
}
